name: Build/Release Stable Candidate

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '*/README.md'
    - '*/LICENSE'
    - '*/.gitignore'
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  build-release-candidate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master Branch
      uses: actions/checkout@v2
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup BuildX
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    - name: Build AMD64 Docker image
      run: docker build --platform=linux/amd64 --load -t ghcr.io/$GITHUB_REPOSITORY:stable-rc .
    - name: Build ARM64v8 Docker image
      run: docker build --platform=linux/arm64 --load -t ghcr.io/$GITHUB_REPOSITORY:stable-rc-arm64v8 -f Dockerfile.arm64v8 .
    - name: Login to GHCR.IO
      run: docker login --username=shrunbr --password=$GITHUB_TOKEN ghcr.io
    - name: Release Stable Candidate
      run: |
        docker push ghcr.io/$GITHUB_REPOSITORY:stable-rc

        docker push ghcr.io/$GITHUB_REPOSITORY:stable-rc-arm64v8